version: '3.3'

services:
  web:
    build: .
    image: rymper/blob
    container_name: blob_djangocontainer
    command: bash -c "(
      cd /app && python3 manage.py makemigrations && \
      python3 manage.py migrate && \
      hupper -m manage runserver 0.0.0.0:8000)"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - db
      - redis
    networks:
      - backend
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: blob_nginx_container
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
      - ./configs/blob.conf:/etc/nginx/conf.d/default.conf
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: blob_rediscontainer
    networks:
      - backend
    expose:
      - "6379"

  db:
    platform: linux/amd64
    image: postgres:15-alpine
    container_name: blob_dbcontainer
    environment:
      POSTGRES_DB: blob
      POSTGRES_USER: blob_dev
      POSTGRES_PASSWORD: blob_dev
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
    networks:
      - backend
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  backend:

configs:
  nginx_conf:
    file: ./configs/blob.conf
