version: '3.9'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile.prod
    container_name: djangocontainer
    image: rymper/blob-ai:latest
    command: bash -c "(cd /app && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py collectstatic --no-input && daphne -b 0.0.0.0 -p 8000 prompt_mkt.asgi:application)"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - backend
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - .:/app
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis_container
    networks:
      - backend
    expose:
      - "6379"

  db:
    image: postgres:15-alpine
    container_name: dbcontainer
    environment:
      POSTGRES_DB: blob
      POSTGRES_USER: blob_dev
      POSTGRES_PASSWORD: blob_dev
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
    networks:
      - backend
    expose:
      - "5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  backend:
configs:
  nginx_conf:
    file: configs/blob.conf